import { StructureType } from "@/types";

export interface TradeEntry {
  order: number;
  trade: string;
  category: string;
  description: string;
  licenseRequired: boolean;
  licenseNote: string;
  budgetPctRange: string; // % of total project cost
  searchKeywords: string; // used for Google/Yelp search
}

// Trades needed for each structure category, in build sequence order.
// budgetPctRange is the typical % of total project cost for that trade.

const RESIDENTIAL_TRADES: TradeEntry[] = [
  {
    order: 1,
    trade: "Site Prep / Excavation",
    category: "Civil",
    description: "Land clearing, grading, excavation for foundation, driveway rough-in, erosion control.",
    licenseRequired: true,
    licenseNote: "Contractor's license required in most states",
    budgetPctRange: "3–6%",
    searchKeywords: "excavation contractor site preparation",
  },
  {
    order: 2,
    trade: "Foundation / Concrete",
    category: "Structural",
    description: "Footings, slab, stem walls, basement walls, or pier drilling. Includes waterproofing.",
    licenseRequired: true,
    licenseNote: "Concrete contractor or general contractor license",
    budgetPctRange: "8–14%",
    searchKeywords: "foundation contractor concrete contractor",
  },
  {
    order: 3,
    trade: "Framing",
    category: "Structural",
    description: "Wall framing, floor systems, roof framing or trusses. Structural sheathing and housewrap.",
    licenseRequired: true,
    licenseNote: "Framing contractor or GC license required",
    budgetPctRange: "12–18%",
    searchKeywords: "framing contractor residential framing",
  },
  {
    order: 4,
    trade: "Roofing",
    category: "Envelope",
    description: "Sheathing, underlayment, shingles or metal roofing, flashing, ridge venting.",
    licenseRequired: true,
    licenseNote: "Roofing contractor license required in most states",
    budgetPctRange: "5–10%",
    searchKeywords: "roofing contractor residential roofing",
  },
  {
    order: 5,
    trade: "Windows & Exterior Doors",
    category: "Envelope",
    description: "Supply and installation of windows, exterior doors, flashing, and weatherstripping.",
    licenseRequired: false,
    licenseNote: "Installer certification recommended; window contractor",
    budgetPctRange: "4–8%",
    searchKeywords: "window installation contractor exterior doors",
  },
  {
    order: 6,
    trade: "Plumbing (Rough)",
    category: "MEP",
    description: "Underground DWV, supply rough-in, drain lines set before concrete or drywall.",
    licenseRequired: true,
    licenseNote: "Licensed plumber required in all states",
    budgetPctRange: "4–8% (rough only)",
    searchKeywords: "licensed plumber residential plumbing contractor",
  },
  {
    order: 7,
    trade: "HVAC (Rough)",
    category: "MEP",
    description: "Duct rough-in, equipment pad, refrigerant line set, ventilation penetrations.",
    licenseRequired: true,
    licenseNote: "HVAC contractor; EPA 608 certification for refrigerants",
    budgetPctRange: "5–10% (rough only)",
    searchKeywords: "HVAC contractor residential heating cooling",
  },
  {
    order: 8,
    trade: "Electrical (Rough)",
    category: "MEP",
    description: "Panel installation, branch circuits, box placement, low-voltage wiring.",
    licenseRequired: true,
    licenseNote: "Licensed electrician required in all states",
    budgetPctRange: "4–8% (rough only)",
    searchKeywords: "licensed electrician residential electrical contractor",
  },
  {
    order: 9,
    trade: "Insulation",
    category: "Envelope",
    description: "Wall, floor, and attic insulation. Blower door test and air sealing.",
    licenseRequired: false,
    licenseNote: "Spray foam requires certified installer; batt is unlicensed",
    budgetPctRange: "2–5%",
    searchKeywords: "insulation contractor residential insulation",
  },
  {
    order: 10,
    trade: "Drywall",
    category: "Interior",
    description: "Hang, tape, mud, and texture. Includes fire-rated assemblies where required.",
    licenseRequired: false,
    licenseNote: "Unlicensed in most states; drywall subcontractor",
    budgetPctRange: "4–7%",
    searchKeywords: "drywall contractor sheetrock installation",
  },
  {
    order: 11,
    trade: "Exterior Siding / Cladding",
    category: "Envelope",
    description: "Install siding, trim, soffits, fascia, and exterior paint.",
    licenseRequired: false,
    licenseNote: "Siding contractor; HardiePlank requires certified installer",
    budgetPctRange: "3–6%",
    searchKeywords: "siding contractor exterior contractor",
  },
  {
    order: 12,
    trade: "Interior Trim / Finish Carpentry",
    category: "Interior",
    description: "Baseboards, door casings, window stools, crown molding, stair railings.",
    licenseRequired: false,
    licenseNote: "Carpenter or finish contractor",
    budgetPctRange: "2–4%",
    searchKeywords: "finish carpenter trim contractor interior carpentry",
  },
  {
    order: 13,
    trade: "Cabinets & Countertops",
    category: "Interior",
    description: "Kitchen and bath cabinetry installation, countertop fabrication and installation.",
    licenseRequired: false,
    licenseNote: "Cabinet installer; countertop fabricator",
    budgetPctRange: "5–12%",
    searchKeywords: "cabinet installer countertop fabricator kitchen contractor",
  },
  {
    order: 14,
    trade: "Flooring",
    category: "Interior",
    description: "Hardwood, LVP, tile, or carpet installation. Subfloor prep included.",
    licenseRequired: false,
    licenseNote: "Flooring contractor; tile work may require license in some states",
    budgetPctRange: "3–7%",
    searchKeywords: "flooring contractor hardwood flooring installation",
  },
  {
    order: 15,
    trade: "Plumbing (Finish)",
    category: "MEP",
    description: "Fixture installation, water heater, trim out, final connections, inspection.",
    licenseRequired: true,
    licenseNote: "Licensed plumber required",
    budgetPctRange: "2–4% (finish only)",
    searchKeywords: "licensed plumber fixture installation trim out",
  },
  {
    order: 16,
    trade: "HVAC (Finish / Start-up)",
    category: "MEP",
    description: "Equipment installation, refrigerant charge, duct balancing, thermostat setup.",
    licenseRequired: true,
    licenseNote: "HVAC contractor; EPA 608 required",
    budgetPctRange: "2–5% (finish only)",
    searchKeywords: "HVAC contractor equipment installation",
  },
  {
    order: 17,
    trade: "Electrical (Finish)",
    category: "MEP",
    description: "Device installation, fixtures, panel trim out, final inspection.",
    licenseRequired: true,
    licenseNote: "Licensed electrician required",
    budgetPctRange: "2–4% (finish only)",
    searchKeywords: "licensed electrician finish electrical",
  },
  {
    order: 18,
    trade: "Painting / Interior Finishes",
    category: "Interior",
    description: "Prime and paint walls, ceilings, trim. Interior and exterior painting.",
    licenseRequired: false,
    licenseNote: "Painting contractor; lead-safe certification if pre-1978",
    budgetPctRange: "2–5%",
    searchKeywords: "painting contractor interior exterior paint",
  },
  {
    order: 19,
    trade: "Landscaping / Final Grade",
    category: "Civil",
    description: "Final grading, topsoil, seeding, erosion control, driveway finish.",
    licenseRequired: false,
    licenseNote: "Landscaper or grading contractor",
    budgetPctRange: "1–4%",
    searchKeywords: "landscaping contractor grading site work",
  },
];

const AGRICULTURAL_TRADES: TradeEntry[] = [
  {
    order: 1,
    trade: "Site Prep / Grading",
    category: "Civil",
    description: "Land clearing, grading, drainage swales, access road, compacted base preparation.",
    licenseRequired: true,
    licenseNote: "Earthwork contractor or GC",
    budgetPctRange: "4–8%",
    searchKeywords: "excavation contractor grading site preparation",
  },
  {
    order: 2,
    trade: "Foundation / Concrete Piers",
    category: "Structural",
    description: "Concrete piers, grade beams, compacted gravel pad, or slab for post-frame buildings.",
    licenseRequired: true,
    licenseNote: "Concrete contractor or GC",
    budgetPctRange: "6–12%",
    searchKeywords: "concrete contractor post-frame foundation",
  },
  {
    order: 3,
    trade: "Post-Frame / Steel Erection",
    category: "Structural",
    description: "Post-frame (pole barn) or pre-engineered steel building erection. Includes purling and girts.",
    licenseRequired: true,
    licenseNote: "Post-frame contractor or metal building erector",
    budgetPctRange: "25–40%",
    searchKeywords: "pole barn builder post frame contractor metal building erector",
  },
  {
    order: 4,
    trade: "Roofing (Metal / Metal Sheeting)",
    category: "Envelope",
    description: "Metal roof panels, ridge cap, flashing, gutters.",
    licenseRequired: false,
    licenseNote: "Metal roofing contractor",
    budgetPctRange: "10–15%",
    searchKeywords: "metal roofing contractor agricultural roofing",
  },
  {
    order: 5,
    trade: "Doors & Sliding / Rolling Doors",
    category: "Envelope",
    description: "Overhead, sliding, and walk-in door installation. Hardware and weather seals.",
    licenseRequired: false,
    licenseNote: "Door contractor or building supplier",
    budgetPctRange: "5–12%",
    searchKeywords: "overhead door contractor sliding barn doors",
  },
  {
    order: 6,
    trade: "Electrical",
    category: "MEP",
    description: "Service entrance, panel, lighting circuits, outlet circuits, 3-phase if needed.",
    licenseRequired: true,
    licenseNote: "Licensed electrician required",
    budgetPctRange: "5–10%",
    searchKeywords: "licensed electrician agricultural electrical",
  },
  {
    order: 7,
    trade: "Plumbing (if included)",
    category: "MEP",
    description: "Water supply, drain lines, frost-free hydrants, wash-down systems.",
    licenseRequired: true,
    licenseNote: "Licensed plumber required",
    budgetPctRange: "3–7%",
    searchKeywords: "licensed plumber agricultural plumbing",
  },
  {
    order: 8,
    trade: "Insulation (if conditioned)",
    category: "Envelope",
    description: "Spray foam or rigid foam for conditioned spaces. Vapor barriers.",
    licenseRequired: false,
    licenseNote: "Insulation contractor",
    budgetPctRange: "2–5%",
    searchKeywords: "insulation contractor spray foam",
  },
  {
    order: 9,
    trade: "Concrete Floors",
    category: "Interior",
    description: "Interior slab, apron slab at doors, equipment pads.",
    licenseRequired: true,
    licenseNote: "Concrete contractor",
    budgetPctRange: "5–10%",
    searchKeywords: "concrete contractor slab floor",
  },
];

const CONTAINER_TRADES: TradeEntry[] = [
  {
    order: 1,
    trade: "Structural Engineer",
    category: "Design",
    description: "PE-stamped drawings for container modifications, openings, and connection details.",
    licenseRequired: true,
    licenseNote: "Licensed Professional Engineer (PE) required",
    budgetPctRange: "1–3%",
    searchKeywords: "structural engineer container home modular",
  },
  {
    order: 2,
    trade: "Site Prep / Foundation",
    category: "Civil",
    description: "Concrete piers, grade beams, or slab at container corner points.",
    licenseRequired: true,
    licenseNote: "Concrete contractor",
    budgetPctRange: "6–12%",
    searchKeywords: "concrete contractor foundation piers",
  },
  {
    order: 3,
    trade: "Container Delivery & Placement",
    category: "Structural",
    description: "Flatbed transport, crane or forklift placement on foundation points.",
    licenseRequired: true,
    licenseNote: "Commercial trucking license + rigging company",
    budgetPctRange: "3–6%",
    searchKeywords: "shipping container delivery crane rental rigging",
  },
  {
    order: 4,
    trade: "Steel Fabrication / Modification",
    category: "Structural",
    description: "Cutting openings, welding connection plates, structural steel reinforcement.",
    licenseRequired: true,
    licenseNote: "AWS-certified welder; structural steel fabricator",
    budgetPctRange: "8–15%",
    searchKeywords: "steel fabricator welder container modification",
  },
  ...RESIDENTIAL_TRADES.filter((t) => t.order >= 6),
];

const OUTBUILDING_TRADES: TradeEntry[] = AGRICULTURAL_TRADES;

const SUSTAINABLE_TRADES: TradeEntry[] = [
  ...RESIDENTIAL_TRADES,
  {
    order: 20,
    trade: "Solar / PV Installer",
    category: "MEP",
    description: "Rooftop or ground-mount PV system, inverter, battery storage, utility interconnect.",
    licenseRequired: true,
    licenseNote: "NABCEP certification recommended; electrical license required",
    budgetPctRange: "5–12%",
    searchKeywords: "solar installer PV system residential solar",
  },
  {
    order: 21,
    trade: "Rainwater / Greywater System",
    category: "MEP",
    description: "Collection tanks, first-flush diverters, filtration, grey water recycling.",
    licenseRequired: true,
    licenseNote: "Plumber required; systems must meet local code",
    budgetPctRange: "2–5%",
    searchKeywords: "rainwater collection greywater system plumber",
  },
];

type StructureCategory = "Residential" | "Agricultural" | "Specialty" | "Outbuilding" | "Sustainable";

const CATEGORY_TRADES: Record<StructureCategory, TradeEntry[]> = {
  Residential: RESIDENTIAL_TRADES,
  Agricultural: AGRICULTURAL_TRADES,
  Specialty: CONTAINER_TRADES,
  Outbuilding: OUTBUILDING_TRADES,
  Sustainable: SUSTAINABLE_TRADES,
};

// Map individual structure types to a category
const STRUCTURE_CATEGORY_MAP: Record<StructureType, StructureCategory> = {
  SINGLE_FAMILY_HOME: "Residential",
  CONTAINER_HOME: "Specialty",
  BARNDOMINIUM: "Residential",
  BARN: "Agricultural",
  LOG_CABIN: "Residential",
  A_FRAME: "Residential",
  SHED: "Outbuilding",
  WORKSHOP: "Outbuilding",
  GARAGE: "Outbuilding",
  TINY_HOME: "Residential",
  DOME_HOME: "Residential",
  QUONSET_HUT: "Agricultural",
  SILO: "Agricultural",
  POLE_BARN: "Agricultural",
  EARTHSHIP: "Sustainable",
  PASSIVE_SOLAR: "Sustainable",
};

export function getTradesForStructure(structureType: StructureType): TradeEntry[] {
  const category = STRUCTURE_CATEGORY_MAP[structureType] ?? "Residential";
  return CATEGORY_TRADES[category] ?? RESIDENTIAL_TRADES;
}
