import { StructureOption } from "@/types";

export const STRUCTURE_OPTIONS: StructureOption[] = [
  {
    value: "SINGLE_FAMILY_HOME",
    label: "Single Family Home",
    description: "Traditional stick-built or modular home",
    icon: "🏠",
    category: "Residential",
    costLevel: 3,
    costNote: "$150–$300/sq ft",
    image: "https://images.unsplash.com/photo-1568605114967-8130f3a36994?auto=format&fit=crop&w=600&q=80",
  },
  {
    value: "CONTAINER_HOME",
    label: "Container Home",
    description: "Built from ISO/Connex shipping containers",
    icon: "📦",
    category: "Residential",
    costLevel: 2,
    costNote: "$100–$175/sq ft",
    image: "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?auto=format&fit=crop&w=600&q=80",
  },
  {
    value: "TINY_HOME",
    label: "Tiny Home",
    description: "Compact, efficient living under 400 sq ft",
    icon: "🏡",
    category: "Residential",
    costLevel: 1,
    costNote: "$30k–$80k total",
    image: "https://images.unsplash.com/photo-1585435557343-3b092031a831?auto=format&fit=crop&w=600&q=80",
  },
  {
    value: "BARNDOMINIUM",
    label: "Barndominium",
    description: "Combined barn and living space",
    icon: "🏚️",
    category: "Agricultural",
    costLevel: 2,
    costNote: "$95–$150/sq ft",
    image: "https://images.unsplash.com/photo-1625602812206-5ec545ca1231?auto=format&fit=crop&w=600&q=80",
  },
  {
    value: "BARN",
    label: "Barn",
    description: "Agricultural storage and livestock building",
    icon: "🏛️",
    category: "Agricultural",
    costLevel: 1,
    costNote: "$35–$75/sq ft",
    image: "https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=600&q=80",
  },
  {
    value: "POLE_BARN",
    label: "Pole Barn",
    description: "Post-frame construction, versatile and economical",
    icon: "🏗️",
    category: "Agricultural",
    costLevel: 1,
    costNote: "$20–$60/sq ft",
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=600&q=80",
  },
  {
    value: "LOG_CABIN",
    label: "Log Cabin",
    description: "Traditional or modern log construction",
    icon: "🪵",
    category: "Specialty",
    costLevel: 3,
    costNote: "$150–$300/sq ft",
    image: "https://images.unsplash.com/photo-1449158743715-0a90ebb6d2d8?auto=format&fit=crop&w=600&q=80",
  },
  {
    value: "A_FRAME",
    label: "A-Frame",
    description: "Distinctive triangular roofline structure",
    icon: "⛺",
    category: "Specialty",
    costLevel: 2,
    costNote: "$100–$200/sq ft",
    image: "https://images.unsplash.com/photo-1518780664697-55e3ad937233?auto=format&fit=crop&w=600&q=80",
  },
  {
    value: "DOME_HOME",
    label: "Dome Home",
    description: "Geodesic or monolithic dome structure",
    icon: "⛩️",
    category: "Specialty",
    costLevel: 3,
    costNote: "$130–$250/sq ft",
    image: "https://images.unsplash.com/photo-1510798831971-661eb04b3739?auto=format&fit=crop&w=600&q=80",
  },
  {
    value: "QUONSET_HUT",
    label: "Quonset Hut",
    description: "Semi-cylindrical corrugated steel structure",
    icon: "🏟️",
    category: "Specialty",
    costLevel: 1,
    costNote: "$25–$70/sq ft",
    image: "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=600&q=80",
  },
  {
    value: "SILO",
    label: "Silo / Round Structure",
    description: "Grain silo conversion or cylindrical build",
    icon: "🗼",
    category: "Specialty",
    costLevel: 3,
    costNote: "$100–$200/sq ft",
    image: "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=600&q=80",
  },
  {
    value: "SHED",
    label: "Shed",
    description: "Storage or utility outbuilding",
    icon: "🏠",
    category: "Outbuilding",
    costLevel: 1,
    costNote: "$15–$50/sq ft",
    image: "https://images.unsplash.com/photo-1558904541-efa843a96f01?auto=format&fit=crop&w=600&q=80",
  },
  {
    value: "WORKSHOP",
    label: "Workshop",
    description: "Dedicated workspace or hobby shop",
    icon: "🔨",
    category: "Outbuilding",
    costLevel: 1,
    costNote: "$25–$75/sq ft",
    image: "https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&w=600&q=80",
  },
  {
    value: "GARAGE",
    label: "Garage",
    description: "Vehicle storage, attached or detached",
    icon: "🚗",
    category: "Outbuilding",
    costLevel: 2,
    costNote: "$50–$100/sq ft",
    image: "https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?auto=format&fit=crop&w=600&q=80",
  },
  {
    value: "EARTHSHIP",
    label: "Earthship",
    description: "Off-grid, earth-built sustainable home",
    icon: "🌍",
    category: "Sustainable",
    costLevel: 4,
    costNote: "$200–$400/sq ft",
    image: "https://images.unsplash.com/photo-1475087542963-13ab5e611954?auto=format&fit=crop&w=600&q=80",
  },
  {
    value: "PASSIVE_SOLAR",
    label: "Passive Solar Home",
    description: "Optimized for natural heating and cooling",
    icon: "☀️",
    category: "Sustainable",
    costLevel: 4,
    costNote: "$200–$350/sq ft",
    image: "https://images.unsplash.com/photo-1501761095094-94d36f57edbb?auto=format&fit=crop&w=600&q=80",
  },
];

export const STRUCTURE_CATEGORIES = [
  "Residential",
  "Agricultural",
  "Specialty",
  "Outbuilding",
  "Sustainable",
] as const;
