import { StructureOption } from "@/types";

export const STRUCTURE_OPTIONS: StructureOption[] = [
  {
    value: "SINGLE_FAMILY_HOME",
    label: "Single Family Home",
    description: "Traditional stick-built or modular home",
    icon: "🏠",
    category: "Residential",
    costLevel: 3,
    costNote: "$150–$300/sq ft",
    image: "/images/structures/single-family-home.jpg",
  },
  {
    value: "CONTAINER_HOME",
    label: "Container Home",
    description: "Built from ISO/Connex shipping containers",
    icon: "📦",
    category: "Residential",
    costLevel: 2,
    costNote: "$100–$175/sq ft",
    image: "/images/structures/container-home.jpg",
  },
  {
    value: "TINY_HOME",
    label: "Tiny Home",
    description: "Compact, efficient living under 400 sq ft",
    icon: "🏡",
    category: "Residential",
    costLevel: 1,
    costNote: "$30k–$80k total",
    image: "/images/structures/tiny-home.jpg",
  },
  {
    value: "BARNDOMINIUM",
    label: "Barndominium",
    description: "Combined barn and living space",
    icon: "🏚️",
    category: "Agricultural",
    costLevel: 2,
    costNote: "$95–$150/sq ft",
    image: "/images/structures/barndominium.jpg",
  },
  {
    value: "BARN",
    label: "Barn",
    description: "Agricultural storage and livestock building",
    icon: "🏛️",
    category: "Agricultural",
    costLevel: 1,
    costNote: "$35–$75/sq ft",
    image: "/images/structures/barn.jpg",
  },
  {
    value: "POLE_BARN",
    label: "Pole Barn",
    description: "Post-frame construction, versatile and economical",
    icon: "🏗️",
    category: "Agricultural",
    costLevel: 1,
    costNote: "$20–$60/sq ft",
    image: "/images/structures/pole-barn.jpg",
  },
  {
    value: "LOG_CABIN",
    label: "Log Cabin",
    description: "Traditional or modern log construction",
    icon: "🪵",
    category: "Specialty",
    costLevel: 3,
    costNote: "$150–$300/sq ft",
    image: "/images/structures/log-cabin.jpg",
  },
  {
    value: "A_FRAME",
    label: "A-Frame",
    description: "Distinctive triangular roofline structure",
    icon: "⛺",
    category: "Specialty",
    costLevel: 2,
    costNote: "$100–$200/sq ft",
    image: "/images/structures/a-frame.jpg",
  },
  {
    value: "DOME_HOME",
    label: "Dome Home",
    description: "Geodesic or monolithic dome structure",
    icon: "⛩️",
    category: "Specialty",
    costLevel: 3,
    costNote: "$130–$250/sq ft",
    image: "/images/structures/dome-home.jpg",
  },
  {
    value: "QUONSET_HUT",
    label: "Quonset Hut",
    description: "Semi-cylindrical corrugated steel structure",
    icon: "🏟️",
    category: "Specialty",
    costLevel: 1,
    costNote: "$25–$70/sq ft",
    image: "/images/structures/quonset-hut.jpg",
  },
  {
    value: "SILO",
    label: "Silo / Round Structure",
    description: "Grain silo conversion or cylindrical build",
    icon: "🗼",
    category: "Specialty",
    costLevel: 3,
    costNote: "$100–$200/sq ft",
    image: "/images/structures/silo.jpg",
  },
  {
    value: "SHED",
    label: "Shed",
    description: "Storage or utility outbuilding",
    icon: "🏠",
    category: "Outbuilding",
    costLevel: 1,
    costNote: "$15–$50/sq ft",
    image: "/images/structures/shed.jpg",
  },
  {
    value: "WORKSHOP",
    label: "Workshop",
    description: "Dedicated workspace or hobby shop",
    icon: "🔨",
    category: "Outbuilding",
    costLevel: 1,
    costNote: "$25–$75/sq ft",
    image: "/images/structures/workshop.jpg",
  },
  {
    value: "GARAGE",
    label: "Garage",
    description: "Vehicle storage, attached or detached",
    icon: "🚗",
    category: "Outbuilding",
    costLevel: 2,
    costNote: "$50–$100/sq ft",
    image: "/images/structures/garage.jpg",
  },
  {
    value: "EARTHSHIP",
    label: "Earthship",
    description: "Off-grid, earth-built sustainable home",
    icon: "🌍",
    category: "Sustainable",
    costLevel: 4,
    costNote: "$200–$400/sq ft",
    image: "/images/structures/earthship.jpg",
  },
  {
    value: "PASSIVE_SOLAR",
    label: "Passive Solar Home",
    description: "Optimized for natural heating and cooling",
    icon: "☀️",
    category: "Sustainable",
    costLevel: 4,
    costNote: "$200–$350/sq ft",
    image: "/images/structures/passive-solar.jpg",
  },
];

export const STRUCTURE_CATEGORIES = [
  "Residential",
  "Agricultural",
  "Specialty",
  "Outbuilding",
  "Sustainable",
] as const;
